### ISSUE TITLE
 build is failing according to the readme

### ISSUE THREAD

**Issue by matkoniecz** [mvexel/overpass-api-python-wrapper#126]
https://github.com/mvexel/overpass-api-python-wrapper#overpass-api-python-wrapper

I am a bit confused as it has `https://travis-ci.org/mvexel/overpass-api-python-wrapper.svg?branch=master` while build failure is about not yet merged pull request #125 ( https://travis-ci.org/github/mvexel/overpass-api-python-wrapper )

Is `branch=master` not working anymore? Maybe I am getting confused by travis-ci interface?

**Comment by dericke** [comment]
Build for master has been failing since 603b7ec , see #119

**Comment by dericke** [comment]
Actually, looking at it again, it appears that 

1. Build has actually been failing since fb1e83c75f6b9e097a62a6003306d0f07b67620b
2. It is only the tests against Python 2.7 and 3.3 that are failing. I created PR #128 to drop these from the Travis config and add the latest Python versions to test against.

**Comment by mvexel** [comment]
Thanks for the PR, @dericke -- merged, should run now
