### ISSUE TITLE
Return timestamps for individual edits

### ISSUE THREAD

**Issue by eoglethorpe** [mvexel/overpass-api-python-wrapper#30]
Maybe I'm missing something but is it possible to return timestamps of individual edits?

**Comment by itiboi** [comment]
What exactly do you means with individual edit? The last time an object node etc. was changed?

Anything regarding timestamps is not implemented as simple query. But since this package is just a wrapper you can send plain OverpassQL requests via [this](https://github.com/mvexel/overpass-api-python-wrapper#use-it).

For details how to use it, please take a look at OpenStreetMap Wiki, especially [this page](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL). If you set the print mode to [verbose](http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Verbose_.28meta.29), you receive a changeset id and and a timestamp, maybe this helps!

**Comment by eoglethorpe** [comment]
Ooooh yup that's what I'm looking for - thanks :+1:
