### ISSUE TITLE
Map query 

### ISSUE THREAD

**Issue by mmd-osm** [mvexel/overpass-api-python-wrapper#40]
To keep the [map query](https://github.com/mvexel/overpass-api-python-wrapper/blob/master/overpass/queries.py#L8) in sync with the main `map` call on osm.org, I'd suggest to take a look at the original query, which is used by Overpass API to implement the map call: https://github.com/drolbr/Overpass-API/blob/master/src/cgi-bin/map#L27.

As an alternative, the /api/map endpoint could be called instead of /api/interpreter, like on osm.org.

**Comment by mvexel** [comment]
Yes, that seems like a good idea. This is trivial to implement but will break the way `MapQuery` works. Right now you would call it like 

`result = api.Get(MapQuery(bbox))` 

Because the `/map` call is a different endpoint is actually a different endpoint, it may be confusing to define the wrapper like this. I propose either a static method:

`map = overpass.Map(bbox)`

or a new instance method:

`map = api.Map(bbox)`

Looking at how we have been designing the wrapper so far, I gravitate towards the latter solution.

**Comment by mvexel** [comment]
It's interesting that I can't find any reference to the `/map` call on the [Overpass API wiki](http://wiki.openstreetmap.org/wiki/Overpass_API) page on OSM...

**Comment by mvexel** [comment]
Does anyone know if there is any more to it than `http://overpass-api.de/api/map?bbox=min_lon,min_lat,max_lon,max_lat`?

**Comment by mmd-osm** [comment]
According to the [original commit](https://github.com/drolbr/Overpass-API/commit/46a0cdd5fa44f56a484adcd80cf48f2879f332c8), the idea was to provide a map call via Overpass API, which matches the [OSM API method map](http://wiki.openstreetmap.org/wiki/API_v0.6#Retrieving_map_data_by_bounding_box:_GET_.2Fapi.2F0.6.2Fmap).

> Does anyone know if there is any more to it than http://overpass-api.de/api/map?bbox=min_lon,min_lat,max_lon,max_lat?

That should really be all. The main OSM site uses the same approach:  
https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/app/assets/javascripts/index/export.js#L45-L48
